"""initial_schema

Revision ID: e51abfb3c70f
Revises: 
Create Date: 2026-03-23 14:24:27.377341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'e51abfb3c70f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    """Check if a table exists in the current database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def _index_exists(table_name: str, index_name: str) -> bool:
    """Check if an index exists in the current database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    
    if table_name not in inspector.get_table_names():
        return False
    
    return index_name in {idx["name"] for idx in inspector.get_indexes(table_name)}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('users'):
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=30), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('plan', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('users', 'ix_users_email'):
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    if not _index_exists('users', 'ix_users_id'):
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    if not _index_exists('users', 'ix_users_username'):
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    if not _table_exists('agents'):
        op.create_table('agents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('funcao', sa.String(length=160), nullable=False),
        sa.Column('tipo', sa.String(length=60), nullable=False),
        sa.Column('linguagem', sa.String(length=40), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('whatsapp', sa.String(length=120), nullable=True),
        sa.Column('instagram', sa.String(length=120), nullable=True),
        sa.Column('api', sa.String(length=255), nullable=True),
        sa.Column('outros', sa.String(length=255), nullable=True),
        sa.Column('outros_nome', sa.String(length=120), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('agents', 'ix_agents_id'):
        op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    if not _index_exists('agents', 'ix_agents_user_id'):
        op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    
    if not _table_exists('billing_events'):
        op.create_table('billing_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('provider', sa.String(length=40), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('billing_events', 'ix_billing_events_id'):
        op.create_index(op.f('ix_billing_events_id'), 'billing_events', ['id'], unique=False)
    if not _index_exists('billing_events', 'ix_billing_events_user_id'):
        op.create_index(op.f('ix_billing_events_user_id'), 'billing_events', ['user_id'], unique=False)
    
    if not _table_exists('conversations'):
        op.create_table('conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=140), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('conversations', 'ix_conversations_id'):
        op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    if not _index_exists('conversations', 'ix_conversations_user_id'):
        op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    
    if not _table_exists('integrations'):
        op.create_table('integrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(length=40), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('config_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('integrations', 'ix_integrations_id'):
        op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    if not _index_exists('integrations', 'ix_integrations_provider'):
        op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    if not _index_exists('integrations', 'ix_integrations_user_id'):
        op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    
    if not _table_exists('marketing_projects'):
        op.create_table('marketing_projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('objective', sa.String(length=160), nullable=False),
        sa.Column('audience', sa.String(length=160), nullable=False),
        sa.Column('offer', sa.String(length=200), nullable=False),
        sa.Column('tone', sa.String(length=60), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('marketing_projects', 'ix_marketing_projects_id'):
        op.create_index(op.f('ix_marketing_projects_id'), 'marketing_projects', ['id'], unique=False)
    if not _index_exists('marketing_projects', 'ix_marketing_projects_user_id'):
        op.create_index(op.f('ix_marketing_projects_user_id'), 'marketing_projects', ['user_id'], unique=False)
    
    if not _table_exists('subscriptions'):
        op.create_table('subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.String(length=40), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('monthly_price', sa.Float(), nullable=False),
        sa.Column('yearly_price', sa.Float(), nullable=True),
        sa.Column('billing_cycle', sa.String(length=20), nullable=False),
        sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('auto_renew', sa.Boolean(), nullable=False),
        sa.Column('seats', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('subscriptions', 'ix_subscriptions_id'):
        op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    if not _index_exists('subscriptions', 'ix_subscriptions_user_id'):
        op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    
    if not _table_exists('usage_logs'):
        op.create_table('usage_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('metric', sa.String(length=50), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(length=60), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('usage_logs', 'ix_usage_logs_id'):
        op.create_index(op.f('ix_usage_logs_id'), 'usage_logs', ['id'], unique=False)
    if not _index_exists('usage_logs', 'ix_usage_logs_metric'):
        op.create_index(op.f('ix_usage_logs_metric'), 'usage_logs', ['metric'], unique=False)
    if not _index_exists('usage_logs', 'ix_usage_logs_user_id'):
        op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    
    if not _table_exists('user_settings'):
        op.create_table('user_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('background_conversation', sa.Boolean(), nullable=False),
        sa.Column('autocomplete', sa.Boolean(), nullable=False),
        sa.Column('trending', sa.Boolean(), nullable=False),
        sa.Column('sequence', sa.Boolean(), nullable=False),
        sa.Column('split_mode', sa.Boolean(), nullable=False),
        sa.Column('language', sa.String(length=20), nullable=False),
        sa.Column('voice', sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('user_settings', 'ix_user_settings_id'):
        op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    if not _index_exists('user_settings', 'ix_user_settings_user_id'):
        op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    
    if not _table_exists('messages'):
        op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if not _index_exists('messages', 'ix_messages_conversation_id'):
        op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    if not _index_exists('messages', 'ix_messages_id'):
        op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _index_exists('messages', 'ix_messages_id'):
        op.drop_index(op.f('ix_messages_id'), table_name='messages')
    if _index_exists('messages', 'ix_messages_conversation_id'):
        op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    if _table_exists('messages'):
        op.drop_table('messages')
    
    if _index_exists('user_settings', 'ix_user_settings_user_id'):
        op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    if _index_exists('user_settings', 'ix_user_settings_id'):
        op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    if _table_exists('user_settings'):
        op.drop_table('user_settings')
    
    if _index_exists('usage_logs', 'ix_usage_logs_user_id'):
        op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    if _index_exists('usage_logs', 'ix_usage_logs_metric'):
        op.drop_index(op.f('ix_usage_logs_metric'), table_name='usage_logs')
    if _index_exists('usage_logs', 'ix_usage_logs_id'):
        op.drop_index(op.f('ix_usage_logs_id'), table_name='usage_logs')
    if _table_exists('usage_logs'):
        op.drop_table('usage_logs')
    
    if _index_exists('subscriptions', 'ix_subscriptions_user_id'):
        op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    if _index_exists('subscriptions', 'ix_subscriptions_id'):
        op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    if _table_exists('subscriptions'):
        op.drop_table('subscriptions')
    
    if _index_exists('marketing_projects', 'ix_marketing_projects_user_id'):
        op.drop_index(op.f('ix_marketing_projects_user_id'), table_name='marketing_projects')
    if _index_exists('marketing_projects', 'ix_marketing_projects_id'):
        op.drop_index(op.f('ix_marketing_projects_id'), table_name='marketing_projects')
    if _table_exists('marketing_projects'):
        op.drop_table('marketing_projects')
    
    if _index_exists('integrations', 'ix_integrations_user_id'):
        op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    if _index_exists('integrations', 'ix_integrations_provider'):
        op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    if _index_exists('integrations', 'ix_integrations_id'):
        op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    if _table_exists('integrations'):
        op.drop_table('integrations')
    
    if _index_exists('conversations', 'ix_conversations_user_id'):
        op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    if _index_exists('conversations', 'ix_conversations_id'):
        op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    if _table_exists('conversations'):
        op.drop_table('conversations')
    
    if _index_exists('billing_events', 'ix_billing_events_user_id'):
        op.drop_index(op.f('ix_billing_events_user_id'), table_name='billing_events')
    if _index_exists('billing_events', 'ix_billing_events_id'):
        op.drop_index(op.f('ix_billing_events_id'), table_name='billing_events')
    if _table_exists('billing_events'):
        op.drop_table('billing_events')
    
    if _index_exists('agents', 'ix_agents_user_id'):
        op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    if _index_exists('agents', 'ix_agents_id'):
        op.drop_index(op.f('ix_agents_id'), table_name='agents')
    if _table_exists('agents'):
        op.drop_table('agents')
    
    if _index_exists('users', 'ix_users_username'):
        op.drop_index(op.f('ix_users_username'), table_name='users')
    if _index_exists('users', 'ix_users_id'):
        op.drop_index(op.f('ix_users_id'), table_name='users')
    if _index_exists('users', 'ix_users_email'):
        op.drop_index(op.f('ix_users_email'), table_name='users')
    if _table_exists('users'):
        op.drop_table('users')
    # ### end Alembic commands ###
