apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alici-ingress
  namespace: alici-prod
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/platform/overview
spec:
  rules:
  - host: api.alici.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alici-api
            port:
              number: 80
