import type { AxiStudioClip, AxiStudioLayer, AxiStudioMode } from '../../../../store/axiStudioStore';
import type { StudioTemplateCatalogItem } from '../../../../types/studioV2';

export type AxiTemplateType = 'photo' | 'video' | 'social' | 'ad';

export interface AxiTemplateDefinition {
  id: string;
  name: string;
  category: string;
  type: AxiTemplateType;
  premium: boolean;
  thumbnailGradient: string;
  previewLabel: string;
  templateJson: {
    canvas: { width: number; height: number; background: string };
    prompt: string;
    duration: number;
    mode: AxiStudioMode;
    layers: AxiStudioLayer[];
    clips: AxiStudioClip[];
    assets: Array<{ id: string; asset_type: string; asset_url: string; role: string }>;
    animations: Array<{
      layer_id: string;
      property: 'x' | 'y' | 'opacity' | 'scale' | 'rotation';
      keyframes: Array<{ time: number; value: number }>;
    }>;
    fonts: Array<{ family: string; weight: number }>;
    audio: Array<{ id: string; label: string; start: number; duration: number; role: string }>;
    editable_regions: Array<{ layer_id: string; label: string; kind: 'text' | 'image' | 'color' | 'cta' }>;
  };
}

export const axiStudioTemplates: AxiTemplateDefinition[] = [
  {
    id: 'hotel-story-offer',
    name: 'Story Pousada Premium',
    category: 'Hotelaria',
    type: 'social',
    premium: false,
    thumbnailGradient: 'linear-gradient(135deg,#0f172a,#164e63 52%,#ff6a00)',
    previewLabel: '9:16 Story',
    templateJson: {
      canvas: { width: 1080, height: 1920, background: '#06111f' },
      prompt: 'Story vertical para pousada tropical com oferta, prova social e CTA para WhatsApp.',
      duration: 15,
      mode: 'video',
      layers: [
        {
          id: 'hotel-bg',
          name: 'Fundo visual',
          kind: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 70,
          y: 48,
          width: 580,
          height: 445,
          rotation: 0,
          color: '#124055',
          start: 0,
          duration: 15,
          editable: true,
          effects: ['cinematic', 'warm'],
        },
        {
          id: 'hotel-title',
          name: 'Titulo da oferta',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 115,
          y: 140,
          width: 500,
          height: 80,
          rotation: 0,
          text: 'Fim de semana perfeito',
          color: '#FFFFFF',
          fontSize: 46,
          fontFamily: 'Inter',
          start: 0,
          duration: 12,
          editable: true,
          animations: [{ property: 'y', keyframes: [{ time: 0, value: 170 }, { time: 0.8, value: 140 }] }],
        },
        {
          id: 'hotel-subtitle',
          name: 'Beneficio',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 0.95,
          blendMode: 'normal',
          x: 120,
          y: 235,
          width: 460,
          height: 72,
          rotation: 0,
          text: 'Reserve direto e ganhe cafe incluso',
          color: '#BFF7FF',
          fontSize: 26,
          fontFamily: 'Inter',
          start: 1,
          duration: 11,
          editable: true,
        },
        {
          id: 'hotel-cta',
          name: 'CTA WhatsApp',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 168,
          y: 405,
          width: 390,
          height: 58,
          rotation: 0,
          text: 'Chamar no WhatsApp',
          color: '#FF6A00',
          fontSize: 30,
          fontFamily: 'Inter',
          start: 10,
          duration: 5,
          editable: true,
        },
      ],
      clips: [
        { id: 'hotel-clip-bg', layerId: 'hotel-bg', track: 'video', label: 'Cena principal', start: 0, duration: 15 },
        { id: 'hotel-clip-title', layerId: 'hotel-title', track: 'text', label: 'Hook', start: 0, duration: 12 },
        { id: 'hotel-clip-benefit', layerId: 'hotel-subtitle', track: 'text', label: 'Beneficio', start: 1, duration: 11 },
        { id: 'hotel-clip-cta', layerId: 'hotel-cta', track: 'overlay', label: 'CTA final', start: 10, duration: 5 },
      ],
      assets: [],
      animations: [{ layer_id: 'hotel-title', property: 'y', keyframes: [{ time: 0, value: 170 }, { time: 0.8, value: 140 }] }],
      fonts: [{ family: 'Inter', weight: 800 }],
      audio: [{ id: 'hotel-beat', label: 'Beat leve tropical', start: 0, duration: 15, role: 'background' }],
      editable_regions: [
        { layer_id: 'hotel-title', label: 'Titulo', kind: 'text' },
        { layer_id: 'hotel-subtitle', label: 'Beneficio', kind: 'text' },
        { layer_id: 'hotel-cta', label: 'CTA', kind: 'cta' },
        { layer_id: 'hotel-bg', label: 'Cor ou imagem de fundo', kind: 'color' },
      ],
    },
  },
  {
    id: 'product-launch-reel',
    name: 'Reels Lancamento',
    category: 'Marketing',
    type: 'video',
    premium: false,
    thumbnailGradient: 'linear-gradient(135deg,#111827,#A020F0 52%,#00F0FF)',
    previewLabel: 'Reels 15s',
    templateJson: {
      canvas: { width: 1080, height: 1920, background: '#050816' },
      prompt: 'Video curto de lancamento com hook forte, tres beneficios e CTA direto.',
      duration: 15,
      mode: 'video',
      layers: [
        {
          id: 'reel-bg',
          name: 'Fundo campanha',
          kind: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 78,
          y: 58,
          width: 560,
          height: 430,
          rotation: 0,
          color: '#111827',
          start: 0,
          duration: 15,
          editable: true,
          effects: ['neon', 'contrast'],
        },
        {
          id: 'reel-hook',
          name: 'Hook',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 112,
          y: 105,
          width: 500,
          height: 96,
          rotation: 0,
          text: 'Pare de perder clientes',
          color: '#00F0FF',
          fontSize: 42,
          fontFamily: 'Inter',
          start: 0,
          duration: 4,
          editable: true,
        },
        {
          id: 'reel-proof',
          name: 'Prova',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 122,
          y: 260,
          width: 470,
          height: 76,
          rotation: 0,
          text: 'Automatize atendimento, leads e vendas',
          color: '#FFFFFF',
          fontSize: 28,
          fontFamily: 'Inter',
          start: 4,
          duration: 7,
          editable: true,
        },
        {
          id: 'reel-cta',
          name: 'CTA',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 162,
          y: 410,
          width: 400,
          height: 58,
          rotation: 0,
          text: 'Teste a AXI agora',
          color: '#FF6A00',
          fontSize: 31,
          fontFamily: 'Inter',
          start: 11,
          duration: 4,
          editable: true,
        },
      ],
      clips: [
        { id: 'reel-bg-clip', layerId: 'reel-bg', track: 'video', label: 'Base', start: 0, duration: 15 },
        { id: 'reel-hook-clip', layerId: 'reel-hook', track: 'text', label: 'Hook', start: 0, duration: 4 },
        { id: 'reel-proof-clip', layerId: 'reel-proof', track: 'text', label: 'Prova', start: 4, duration: 7 },
        { id: 'reel-cta-clip', layerId: 'reel-cta', track: 'overlay', label: 'CTA', start: 11, duration: 4 },
      ],
      assets: [],
      animations: [
        { layer_id: 'reel-hook', property: 'opacity', keyframes: [{ time: 0, value: 0 }, { time: 0.4, value: 1 }] },
        { layer_id: 'reel-cta', property: 'scale', keyframes: [{ time: 11, value: 0.92 }, { time: 11.4, value: 1 }] },
      ],
      fonts: [{ family: 'Inter', weight: 900 }],
      audio: [{ id: 'reel-impact', label: 'Beat impacto', start: 0, duration: 15, role: 'background' }],
      editable_regions: [
        { layer_id: 'reel-hook', label: 'Hook', kind: 'text' },
        { layer_id: 'reel-proof', label: 'Prova', kind: 'text' },
        { layer_id: 'reel-cta', label: 'CTA', kind: 'cta' },
      ],
    },
  },
  {
    id: 'restaurant-feed-ad',
    name: 'Anuncio Restaurante',
    category: 'Restaurante',
    type: 'ad',
    premium: true,
    thumbnailGradient: 'linear-gradient(135deg,#1c1917,#7c2d12 52%,#FF6A00)',
    previewLabel: 'Feed 1:1',
    templateJson: {
      canvas: { width: 1080, height: 1080, background: '#1c1917' },
      prompt: 'Post quadrado para restaurante com oferta do dia e CTA de pedido.',
      duration: 8,
      mode: 'photo',
      layers: [
        {
          id: 'food-bg',
          name: 'Fundo cardapio',
          kind: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 85,
          y: 70,
          width: 550,
          height: 410,
          rotation: 0,
          color: '#2b160d',
          start: 0,
          duration: 8,
          editable: true,
          effects: ['warm'],
        },
        {
          id: 'food-title',
          name: 'Oferta do dia',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 122,
          y: 120,
          width: 500,
          height: 76,
          rotation: 0,
          text: 'Oferta do dia',
          color: '#FFFFFF',
          fontSize: 46,
          fontFamily: 'Inter',
          start: 0,
          duration: 8,
          editable: true,
        },
        {
          id: 'food-price',
          name: 'Preco',
          kind: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
          x: 150,
          y: 315,
          width: 350,
          height: 70,
          rotation: 0,
          text: 'A partir de R$ 29,90',
          color: '#FF6A00',
          fontSize: 34,
          fontFamily: 'Inter',
          start: 0,
          duration: 8,
          editable: true,
        },
      ],
      clips: [
        { id: 'food-bg-clip', layerId: 'food-bg', track: 'video', label: 'Base', start: 0, duration: 8 },
        { id: 'food-title-clip', layerId: 'food-title', track: 'text', label: 'Oferta', start: 0, duration: 8 },
        { id: 'food-price-clip', layerId: 'food-price', track: 'overlay', label: 'Preco', start: 0, duration: 8 },
      ],
      assets: [],
      animations: [],
      fonts: [{ family: 'Inter', weight: 800 }],
      audio: [],
      editable_regions: [
        { layer_id: 'food-title', label: 'Oferta', kind: 'text' },
        { layer_id: 'food-price', label: 'Preco', kind: 'text' },
        { layer_id: 'food-bg', label: 'Cor ou imagem do produto', kind: 'color' },
      ],
    },
  },
];

export function templateToStudioSnapshot(template: AxiTemplateDefinition) {
  return {
    mode: template.templateJson.mode,
    prompt: template.templateJson.prompt,
    duration: template.templateJson.duration,
    layers: template.templateJson.layers,
    clips: template.templateJson.clips,
    selectedLayerId: template.templateJson.editable_regions[0]?.layer_id ?? template.templateJson.layers[0]?.id ?? null,
  };
}

export function catalogItemToTemplate(item: StudioTemplateCatalogItem): AxiTemplateDefinition {
  const gradients: Record<string, string> = {
    Hotelaria: 'linear-gradient(135deg,#0f172a,#164e63 52%,#ff6a00)',
    Marketing: 'linear-gradient(135deg,#111827,#A020F0 52%,#00F0FF)',
    Restaurante: 'linear-gradient(135deg,#1c1917,#7c2d12 52%,#FF6A00)',
  };
  const templateJson = item.template_json as AxiTemplateDefinition['templateJson'];
  return {
    id: item.id,
    name: item.name,
    category: item.category,
    type: item.type,
    premium: item.premium,
    thumbnailGradient: gradients[item.category] ?? 'linear-gradient(135deg,#07111f,#12313d 52%,#00F0FF)',
    previewLabel: `${templateJson.canvas?.width ?? 1080}x${templateJson.canvas?.height ?? 1920}`,
    templateJson,
  };
}
